### ISSUE TITLE
[Feature request] Live Preview support needed

### ISSUE THREAD

**Issue by DutchPete** [erykwalder/quoth#1]
I use embeds/transclusions a lot, and this plug-in seems interesting. I have fully embraced Live Preview as that is the future anyway and I prefer it.

Please make your plug-in work in LP.

**Comment by erykwalder** [comment]
Hi, this is definitely on the roadmap since live mode will end up being default.

**Comment by DutchPete** [comment]
Excellent 👍, thank you.
