### ISSUE TITLE
Cannot Install 0.6  - 404 Error

### ISSUE THREAD

**Issue by rapatel0** [erykwalder/quoth#10]
Seems like a typo somewhere 

![image](https://user-images.githubusercontent.com/18704704/151727004-1e5ccdb3-98a9-4f3f-b28b-491d3ec60fa3.png)

**Comment by erykwalder** [comment]
Try now. I unfortunately don't have a release process set up, so I'm still doing it by hand. Let me know if there are any issues :)

**Comment by rapatel0** [comment]
Working now. 

Thanks
