### ISSUE TITLE
Failing to Load on Mobile

### ISSUE THREAD

**Issue by iamrecursion** [erykwalder/quoth#12]
I've got an issue where Quoth is failing to load on mobile (iOS, Obsidian Version 1.1.0 (37)).

The exact error message is (grabbed using [Obsidian REPL](https://github.com/ktemkin/obsidian-repl)):

```
Plugin failure: quoth
SyntaxError: Invalid regular expression: invalid group specifier name.
```

**Comment by erykwalder** [comment]
Just pushed the fix for this and tested on iOS. Thanks for the error message, it was super helpful.

Please let me know if you continue to have any issues.

**Comment by iamrecursion** [comment]
Thanks for such a speedy fix! It loads fine now on the latest inside mobile build! ^^
