### ISSUE TITLE
[Feature request] Don't show block title

### ISSUE THREAD

**Issue by vorpalvorpal** [erykwalder/quoth#15]
If I embed "test#heading" it would be nice if there was an option to not show the heading in the embed, just the content after the heading. I've tried to use the 'after:' syntax but it doesn't seem to work for headings (or I'm misunderstanding it).

test.md
```
foobar

# Heading

this is a test
```

the following embed
```quoth
path: [[test#Heading]]
heading: false
```

would show
```
this is a test
```

rather than
```
# Heading

this is a test
```

**Comment by erykwalder** [comment]
To use `after`, the body would be:
```
path: [[test#Heading]]
ranges: after "# Heading"
```

I just tested again, so it should work, but let me know if you have troubles.

In order to not add too many features, I'd prefer to keep it to this syntax for now, since it allows for more broad functionality.

**Comment by vorpalvorpal** [comment]
Thanks. 

I fiddled around for ages trying to get something like that to work, but somehow just completely misunderstood the documentation.
