### ISSUE TITLE
[Feature Request] Live update references when source changes

### ISSUE THREAD

**Issue by wwjCMP** [erykwalder/quoth#3]
When display mode is "embedded", the  bidirectional linking in quote can't be open as in inline mode or the standard embed way. 

Is this a bug?

**Comment by wwjCMP** [comment]
When using inline mode, the quote content appear incomplete in reading view in some cases.

**Comment by erykwalder** [comment]
> When display mode is "embedded", the bidirectional linking in quote can't be open as in inline mode or the standard embed way.
> 
> Is this a bug?

Yes! Will investigate and get fixed with the next release.

**Comment by erykwalder** [comment]
> When using inline mode, the quote content appear incomplete in reading view in some cases.

Are you able to share an example of a file quoted and when it doesn't not load all the content? Thanks!

**Comment by wwjCMP** [comment]
The modified content isn't displayed correctly in the reading view
![Snipaste_2022-01-06_13-14-30](https://user-images.githubusercontent.com/32979859/148333592-1ba2044c-9530-4018-973f-ac596f754fa5.jpg)

**Comment by erykwalder** [comment]
Can you copy the quoth block and share it for this example?

Also, just to check. Are you describing a situation where you have both the source of the quoth open and the reference open, and when you change the source the reference doesn't update?

**Comment by wwjCMP** [comment]
> 
Yes, the reference only updates in the editing view, but not in the reading view. And in embedded mode, everything works fine.

```quoth
file: [[Vscode]]
heading: #ABC
join: " -- "
display: inline
```

**Comment by erykwalder** [comment]
Ok, if I'm understanding correctly, I think it's just that the reference (code block) isn't being reprocessed when the source is updating. I think this should happen for both embedded and inline code blocks, but if you change from one mode to the other, it will reload it, which may throw off debugging.

I believe if you close and reopen the reference (or navigate away and back), it will have been updated, is that correct? All the tests I've done have worked that way so far.

If that is what's happening, then maybe as a feature I can add reloading of the reference when the source is changed.

**Comment by mitsukiyouko555** [comment]
>  think it's just that the reference (code block) isn't being reprocessed when the source is updating. I think this should happen for both embedded and inline code blocks, but if you change from one mode to the other, it will reload it, which may throw off debugging.

yes thats very true - having line updates/auto refresh would be SOO helpful! loving Quoth so far, thank you for making it :) 

btw is there a timeline for when the auto refresh will be implemented? :)
