### ISSUE TITLE
[Feature Request] Update quoth blocks when reference filename changes

### ISSUE THREAD

**Issue by DutchPete** [erykwalder/quoth#4]
In a quoth the file name is 1 of the elements shown. When the note name changes references to that note in other notes are amended automatically, but not in a quoth.

**Comment by erykwalder** [comment]
This is on the roadmap. Unfortunately it isn't covered by obsidian's auto updates, so it will have to be done manually until separate tracking is done.

**Comment by DutchPete** [comment]
Yes, I realize that, it is the same for the excellent *Numbered headings* plug-in.
I just meant to raise the issue.
