### ISSUE TITLE
"Quoth block error: Cannot read property 'frontmatter' of undefined" on non .md file extensions

### ISSUE THREAD

**Issue by Hunanbean** [erykwalder/quoth#7]
This is all i can get from this plugin.   `"Quoth block error: Cannot read property 'frontmatter' of undefined"`
Hopefully just user error.

Thank you

**Comment by Hunanbean** [comment]
Ok, it seems that if the file does not have an .md extension i get that message. Please allow any file extension, as i am using this specifically to try to bring in c++ source code to be displayed. It works fine, as long as i change the extension from cpp to md.

Thank you

**Comment by erykwalder** [comment]
This will be resolved with the next release.
