### ISSUE TITLE
Request: Please enable quoth content definitions.

### ISSUE THREAD

**Issue by Hunanbean** [erykwalder/quoth#8]
Please enable quoth content definitions, such as
 type: code, or type:c++

or perhaps
--Using apostrophes here to represent back quotes--
```
'''quoth c++
path:[[Files/CodeExample.cpp]]
'''

'''quoth js
path:[[Files/EasyExample.js]]
'''
```

allowing quoth to display, using the built in code highlighting feature.

Thank you

**Comment by erykwalder** [comment]
I added this based on file extension. If for some reason that doesn't work, you can open another issue.

**Comment by Hunanbean** [comment]
That seems to be working quite well.

Thank you very much!
